In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
    ]

In [4]:
## Define the vecabulary size
vec_size=10000

In [5]:
## One Hot Representation
one_hot_repr = [one_hot(words,vec_size) for words in sent]
one_hot_repr

[[4604, 134, 2290, 356],
 [4604, 134, 2290, 1527],
 [4604, 9266, 2290, 6635],
 [9292, 1038, 1012, 8025, 3223],
 [9292, 1038, 1012, 8025, 6517],
 [6085, 4604, 2033, 2290, 6882],
 [1758, 6304, 7125, 8025]]

In [6]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4604  134 2290  356]
 [   0    0    0    0 4604  134 2290 1527]
 [   0    0    0    0 4604 9266 2290 6635]
 [   0    0    0 9292 1038 1012 8025 3223]
 [   0    0    0 9292 1038 1012 8025 6517]
 [   0    0    0 6085 4604 2033 2290 6882]
 [   0    0    0    0 1758 6304 7125 8025]]


In [9]:
## Feature Representation
dim=10
model = Sequential()
model.add(Embedding(vec_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 2s 2s/step


array([[[ 0.00235089, -0.00681648, -0.04284845, -0.03729353,
          0.0415836 ,  0.00391976, -0.02395814,  0.01499375,
         -0.03072491, -0.00320804],
        [ 0.00235089, -0.00681648, -0.04284845, -0.03729353,
          0.0415836 ,  0.00391976, -0.02395814,  0.01499375,
         -0.03072491, -0.00320804],
        [ 0.00235089, -0.00681648, -0.04284845, -0.03729353,
          0.0415836 ,  0.00391976, -0.02395814,  0.01499375,
         -0.03072491, -0.00320804],
        [ 0.00235089, -0.00681648, -0.04284845, -0.03729353,
          0.0415836 ,  0.00391976, -0.02395814,  0.01499375,
         -0.03072491, -0.00320804],
        [ 0.01959481, -0.04566355, -0.02953751,  0.02877957,
         -0.00443441, -0.01889149, -0.01363713,  0.03819347,
         -0.02011435, -0.02324287],
        [ 0.02872255,  0.03104473, -0.00651038, -0.00196815,
          0.02644452,  0.01968808, -0.0385897 , -0.02542507,
          0.02016535, -0.04895535],
        [ 0.03869921, -0.02696084,  0.0497557 ,  0.0